### ISSUE TITLE
Hide the Room Code

### ISSUE THREAD

**Issue by SimondeGrasse** [wsun/multibuzzer#23]
Hey, is there a possibility to hide the Room Code or to make it invisible? Maybe with a button.  I want to use your buzzer in a Livestream and don't want other people to join the room so easy.

**Comment by wsun** [comment]
Hi there! The easiest thing to do would probably be to modify the HTML on your page (and delete it from the visible URL in your web browser). If you're using Firefox or Chrome, I've made a [short video](https://www.loom.com/share/f8bb9b327fbb4031aaab690a79d78168) to show how you can do this - if you're using a different browser and aren't sure how to do this, happy to help as well, just let me know.

**Comment by SimondeGrasse** [comment]
Thank you for the fast help. FYI I've tested it with Opera GX and it worked too

**Comment by wsun** [comment]
Awesome, glad to hear it worked out!
