### ISSUE TITLE
Can we do for on Room only

### ISSUE THREAD

**Issue by StavanAdhyaru** [wsun/multibuzzer#41]
Hi, I have on requirement.
Can we create only one Room for the buzzer game?
so that we do not have to generate room code every time?

If that is possible through your code, please let me know?
Thank you so much for this.

**Comment by wsun** [comment]
Hi Stavan! The current implementation only supports randomly-generated rooms, but you could fork this repo and adjust the UUID function `lobbyConfig` on the server to return a single code instead of a randomly-generated one.
