### ISSUE TITLE
Production build and hosting

### ISSUE THREAD

**Issue by Sahelmulagund** [wsun/multibuzzer#43]
Could you please link a guide on how to host such project where server and client Is on the same project? After running yarn build, the production build requires the server to be run differently.

**Comment by wsun** [comment]
Hi Sahel! I just added a few more details to the README, but in short - yes after building the React app, you will need to configure your environment to run the server file, potentially via `yarn start`. Any environment that can run a Node app should be a fit! Hopefully this helps.

**Comment by Sahelmulagund** [comment]
Thank you for your response @wsun ! You’re right, i am able to start the server independently!
