### ISSUE TITLE
A chat-function - only host can see - but open it to clients

### ISSUE THREAD

**Issue by o0Julia0o** [wsun/multibuzzer#50]
for quiz-game with guess-questions a chat would be nice, where the host can see the written chat. And after closing the chat-time he can show the chat to all clients.

**Comment by wsun** [comment]
I think this would be a nice feature, but unfortunately don't have the bandwidth to implement a full chat interface - and besides, there are other chat apps (Zoom, Discord, Slack, Teams, etc) that do a great job of this already. You're welcome to fork this repo and give it a shot though!

**Comment by o0Julia0o** [comment]
Hm, so some words per chatfield would do the thing. To write in a guess and the other players can´t see the guess. The host doesn need to write at all and the client don´t have to see the chat of the other players of course.
