### ISSUE TITLE
script-error

### ISSUE THREAD

**Issue by o0Julia0o** [wsun/multibuzzer#52]
trying to join with ie11:

https://i.imgur.com/bR6eh60.png
https://d1r35dehfyh21b.cloudfront.net/static/js/2.2232b494.chunk.js

**Comment by wsun** [comment]
Appreciate you sharing this! Unfortunately won't fix this one - IE11 was retired earlier this year by Microsoft, and is scheduled to be permanently disabled in a couple of months, so I encourage anyone still using it to upgrade to Edge or another modern browser.

**Comment by o0Julia0o** [comment]
The problem is, that office still uses IE internly. And if you implement you tool within a office-tool like powerpoint (webviewer plugin or inbuild powerpoint-tool for viewing webites live) it is using IE11-engine. So - in a way IE11 is not dead and a lot of years won´t be.
