### ISSUE TITLE
Spacebar Buzzing Interaction

### ISSUE THREAD

**Issue by elehman16** [wsun/multibuzzer#9]
Should pressing the spacebar when the buzzer is "locked" result in a player being able to buzz? This currently seems to be the case. Thank you!

**Comment by wsun** [comment]
Oof that shouldn't happen and definitely is a bug, I'll get a fix out for this shortly. Thank you for letting me know!

**Comment by wsun** [comment]
Fixed in e18a39f0c95a048541b07fea0f3df6dc35678ac4 and deployed, thank you again for the report!
